[package]
name = "rust-ffmpeg-examples"
version = "0.1.0"
authors = ["Miguel Palhas <mpalhas@gmail.com>"]
edition = "2018"

[dependencies]
ffmpeg-dev = { git = "https://github.com/naps62/ffmpeg-dev-rs", rev = "868dbd6" }
clap = {version = "3.0.0-beta.1"}
